version: "2.1"
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:3.0.10.1567-ls198
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=100
      - TZ=${TZ}
    volumes:
      - ${LOCAL_PATH}/docker/data/sonarr:/config
      - ${LOCAL_PATH}/plex/media/series:/tv 
      - ${LOCAL_PATH}/datos/downloads:/downloads
    ports:
      - 8900:8989
    restart: unless-stopped
