version: "2.1"
services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ${LOCAL_PATH}/docker/data/prowlarr:/config
    ports:
      - 9600:9696
    restart: unless-stopped
