version: "2.1"
services:
  radarr:
    image: lscr.io/linuxserver/radarr:4.3.2
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=100
      - TZ=${TZ}
    volumes:
      - ${LOCAL_PATH}/docker/data/radarr:/config
      - ${LOCAL_PATH}/plex/media/peliculas/:/movies
      - ${LOCAL_PATH}/datos/downloads:/downloads
    ports:
      - 7800:7878
    restart: unless-stopped
