version: "2.1"
services:
  jackett:
    image: lscr.io/linuxserver/jackett:0.20.2603
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - AUTO_UPDATE=true #optional
      #optional - RUN_OPTS=<run options here> 
    volumes:
      - ${LOCAL_PATH}/docker/data/jackett:/config
      - ${LOCAL_PATH}/datos/downloads:/downloads
    ports:
      - 9101:9117
    restart: unless-stopped
