version: "3.9"
    
services:
  db:
    image: mysql:5.7
    volumes:
      - ${LOCAL_PATH}/data/wordpress/db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${WORDPRESS_DB_NAME}
      MYSQL_USER: ${WORDPRESS_DB_USER}
      MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD}
    
  wordpress:
    depends_on:
      - db
    image: wordpress:5.9.2-apache
    volumes:
      - ${LOCAL_PATH}/data/wordpress/data:/var/www/html
    ports:
      - "800:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
volumes:
  db_data: {}
  wordpress_data: {}

