version: '3.6'
services:
  telegraf:
    image: telegraf:1.25.0
    container_name: telegraf
    volumes:
    - ${LOCAL_PATH}/docker/data/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - influxdb
    links:
      - influxdb
    restart: unless-stopped
    ports:
    - '8155:8125/udp'
    - '9223:9273'

  influxdb:
    image: influxdb:1.8.10
    container_name: influxdb
    environment:
      - TZ=${TZ}
      - INFLUXDB_DB=${INFLUXDB_DB}
      - INFLUXDB_ADMIN_USER=${INFLUXDB_ADMIN_USER}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}
    ports:
      - '8886:8086'
      - '8883:8083'
    volumes:
      - ${LOCAL_PATH}/docker/data/influxdb/imports:/imports
      - ${LOCAL_PATH}/docker/data/influxdb/influxdb_data:/var/lib/influxdb
    restart: unless-stopped

