version: "2.1"
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:10.8.8
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ={TZ}
      - JELLYFIN_PublishedServerUrl=video.aroxcloud.com #optional
    volumes:
      - ${LOCAL_PATH}/docker/data/jellyfin:/config
      - ${LOCAL_PATH}/plex/media/series:/data/tvshows
      - ${LOCAL_PATH}/plex/media/peliculas:/data/movies
      - ${LOCAL_PATH}/plex/media/documentales:/data/documentary
      - ${LOCAL_PATH}/plex/media/musica:/data/music
    ports:
      - 8960:8096
      #optional - 8920:8920 
      #optional - 7359:7359/udp 
      #optional - 1900:1900/udp 
    restart: unless-stopped
